language: python
python: "2.7"
before_install:
install: 
- mkdir -p ~/sites/bodl-dmt-svc
- cd ~/sites/bodl-dmt-svc
- git clone https://github.com/bodleian/dmt.manifestcompiler.git ./
#- sudo apt-get update && sudo apt-get upgrade -y -q && sudo apt-get dist-upgrade -y -q && sudo apt-get -y -q autoclean && sudo apt-get -y -q autoremove
- sudo adduser --disabled-password --gecos '' bodl-dmt-svc && sudo adduser bodl-dmt-svc sudo && sudo echo '%sudo ALL=ALL NOPASSWD:ALL' >> /etc/sudoers && su - bodl-dmt-svc && mkdir -p sites/bodl-loris-svc
#COPY / ~/sites/bodl-dmt-svc/

# -------------------------------------------------------------------------
# ---------------- IN UBUNTU 14 PILLOW REQS OPENJPEG 2.0  -----------------
# -------------------------------------------------------------------------

# http://shortrecipes.blogspot.co.uk/2014/06/python-34-and-pillow-24-with-jpeg2000.html
# http://stackoverflow.com/questions/1099981/why-cant-python-find-shared-objects-that-are-in-directories-in-sys-path

#- sudo apt-get install -y -q wget cmake make
f#- mkdir -p ~/sites/bodl-dmt-svc/Downloads && cd ~/sites/bodl-dmt-svc/Downloads && wget http://downloads.sourceforge.net/project/openjpeg.mirror/2.0.1/openjpeg-2.0.1.tar.gz && tar xzvf openjpeg-2.0.1.tar.gz && cd openjpeg-2.0.1/ && cmake . && make && sudo make install && export LD_LIBRARY_PATH=/usr/local/lib

# -------------------------------------------------------------------------

- apt-get -y install $(cat ~/sites/bodl-dmt-svc/ubuntu_requirements)

# -------------------------------------------------------------------------
# --------------------------- GET KAKADU ----------------------------------
# -------------------------------------------------------------------------

# change Kakadu_v<number>.zip for different versions: 64, 72, 74, etc.

- cd ~/sites/bodl-dmt-svc/Downloads && curl --user admn2410:PaulB0wl3s -o Kakadu_v74.zip https://databank.ora.ox.ac.uk/dmt/datasets/Kakadu/Kakadu_v74.zip && unzip -d kakadu Kakadu_v74.zip

# -------------------------------------------------------------------------

- cd ~/sites/bodl-dmt-svc/Downloads && wget http://www.python.org/ftp/python/2.7.6/Python-2.7.6.tgz --no-check-certificate && tar zxfv Python-2.7.6.tgz && cd ~/sites/bodl-dmt-svc/Downloads/Python-2.7.6
- ~/sites/bodl-dmt-svc/Downloads/Python-2.7.6/configure --prefix=~/sites/bodl-dmt-svc/python/2.7.6 --enable-unicode=ucs4 --enable-shared LDFLAGS="-Wl,-rpath=~/sites/bodl-dmt-svc/python/2.7.6/lib"
- make
- make install
- cd ~/sites/bodl-dmt-svc/Downloads && wget --no-check-certificate https://pypi.python.org/packages/source/d/distribute/distribute-0.6.49.tar.gz && tar zxfv distribute-0.6.49.tar.gz 
- ~/sites/bodl-dmt-svc/python/2.7.6/bin/python ~/sites/bodl-dmt-svc/Downloads/distribute-0.6.49/distribute_setup.py
- ~/sites/bodl-dmt-svc/python/2.7.6/bin/easy_install pip
- ~/sites/bodl-dmt-svc/python/2.7.6/bin/pip install virtualenv
- mkdir ~/sites/bodl-dmt-svc/.buildout && cd ~/sites/bodl-dmt-svc/.buildout && mkdir eggs && mkdir downloads && mkdir extends && echo "[buildout]" && echo "eggs-directory = ~/sites/bodl-dmt-svc/.buildout/eggs" && echo "download-cache = ~/sites/bodl-dmt-svc/.buildout/downloads" && echo "extends-cache = ~/sites/bodl-dmt-svc/.buildout/extends" >> ~/sites/bodl-dmt-svc/.buildout/default.cfg
- cd ~/sites/bodl-dmt-svc && ~/sites/bodl-dmt-svc/python/2.7.6/bin/virtualenv . && . bin/activate && pip install zc.buildout && pip install distribute && buildout init && buildout -c development_docker.cfg
- cd ~/sites/bodl-dmt-svc/ && . bin/activate && cd ~/sites/bodl-dmt-svc/src/loris && python setup.py install
- ln -s /usr/include/freetype2 freetype && ln -s /usr/lib/`uname -i`-linux-gnu/libfreetype.so /usr/lib/ && ln -s /usr/lib/`uname -i`-linux-gnu/libjpeg.so /usr/lib/ && ln -s /usr/lib/`uname -i`-linux-gnu/libz.so /usr/lib/ && ln -s /usr/lib/`uname -i`-linux-gnu/liblcms.so /usr/lib/ && ln -s /usr/lib/`uname -i`-linux-gnu/libtiff.so /usr/lib/ && ln -s /usr/lib/`uname -i`-linux-gnu/libopenjp2.so /usr/lib/
- cd ~/sites/bodl-dmt-svc/var/images && curl --user admn2410:PaulB0wl3s -o 67352ccc-d1b0-11e1-89ae-279075081939.jp2 http://databank.ora.ox.ac.uk/dmt/datasets/Images/67352ccc-d1b0-11e1-89ae-279075081939.jp2 && chmod 777 67352ccc-d1b0-11e1-89ae-279075081939.jp2
- cd ~/sites/bodl-dmt-svc/ && . bin/activate && pip install pytest && py.test ~/sites/bodl-dmt-svc/tests/
- cd ~/sites/bodl-dmt-svc/parts && wget --no-check-certificate https://pypi.python.org/packages/source/i/iiif-validator/iiif-validator-0.9.1.tar.gz && tar zxfv iiif-validator-0.9.1.tar.gz
- sudo apt-get -y install libmagic-dev libxml2-dev libxslt-dev && cd ~/sites/bodl-dmt-svc && . bin/activate && pip install bottle && pip install python-magic && pip install lxml && pip install Pillow

# -------------------------------------------------------------------------
# -------------------  START SERVER, - VALIDATOR   ----------------------
# -------------------------------------------------------------------------

#validator needs to - in same intermediate container as the apache start

- chown -R bodl-loris-svc:bodl-loris-svc ~/sites/bodl-dmt-svc
#WORKDIR ~/sites/bodl-dmt-svc
#EXPOSE 8080
- cd ~/sites/bodl-dmt-svc/bin/ && chmod +x lorisctl && sleep 2 && ./lorisctl start && cd ~/sites/bodl-dmt-svc/ && . bin/activate && cd ~/sites/bodl-dmt-svc/parts/iiif-validator-0.9.1/ && ./iiif-validate.py -s 127.0.0.1:8080 -p 'loris' -i 67352ccc-d1b0-11e1-89ae-279075081939.jp2 --version=2.0 -v

script:
- python src/dmt.manifestcompiler/dmt/manifestcompiler/importFiles.py -p src/dmt.manifestcompiler/dmt/manifestcompiler/test/images/ -t jp2 -i http://example.com/images/ -m http://example.com/meta/ -ht 500 -wt 500
- python src/dmt.manifestcompiler/dmt/manifestcompiler/importMETS.py -p src/dmt.manifestcompiler/dmt/manifestcompiler/test/xml/mets.xml -i http://example.com/images/ -m http://example.com/meta/ -ht 500 -wt 500
after_success:
